/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TapiceriaSantiagoRouteImport } from './routes/tapiceria-santiago'
import { Route as TapiceroSantiagoRouteImport } from './routes/tapicero-santiago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapiceriaSantiagoRoute = TapiceriaSantiagoRouteImport.update({
  id: '/tapiceria-santiago',
  path: '/tapiceria-santiago',
  getParentRoute: () => rootRouteImport,
} as any)
const TapiceroSantiagoRoute = TapiceroSantiagoRouteImport.update({
  id: '/tapicero-santiago',
  path: '/tapicero-santiago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tapiceria-santiago': typeof TapiceriaSantiagoRoute
  '/tapicero-santiago': typeof TapiceroSantiagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tapiceria-santiago': typeof TapiceriaSantiagoRoute
  '/tapicero-santiago': typeof TapiceroSantiagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tapiceria-santiago': typeof TapiceriaSantiagoRoute
  '/tapicero-santiago': typeof TapiceroSantiagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tapiceria-santiago' | '/tapicero-santiago'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tapiceria-santiago' | '/tapicero-santiago'
  id: '__root__' | '/' | '/tapiceria-santiago' | '/tapicero-santiago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TapiceriaSantiagoRoute: typeof TapiceriaSantiagoRoute
  TapiceroSantiagoRoute: typeof TapiceroSantiagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tapiceria-santiago': {
      id: '/tapiceria-santiago'
      path: '/tapiceria-santiago'
      fullPath: '/tapiceria-santiago'
      preLoaderRoute: typeof TapiceriaSantiagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tapicero-santiago': {
      id: '/tapicero-santiago'
      path: '/tapicero-santiago'
      fullPath: '/tapicero-santiago'
      preLoaderRoute: typeof TapiceroSantiagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TapiceriaSantiagoRoute: TapiceriaSantiagoRoute,
  TapiceroSantiagoRoute: TapiceroSantiagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
